services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spring:
    build: .
    image: spring
    ports:
      - "8080:8080"

  front:
    build: ./frontend
    image: front
    ports:
      - "80:80"
    depends_on:
      - "spring"

  test:
    build: .
    command: bash -c "gradle clean test"
    volumes:
      - .:/usr/src/app
      - ~/.gradle:/root/.gradle
    depends_on:
      - "postgres"
      - "spring"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
